spring:
  application:
    name: eatWise

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/assignment2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
